### PR TITLE
[Doc] Fix `pip` `requirements.txt` path in build instructions

### PR DESCRIPTION
**Pull request by foundrytom**
Inadvertently missed in #312.

### CODE REVIEW

**Comment by feltech** [comment]
Trying to find other missed references that should have been updated, just a couple of minor ones
* `StubManager.py:StubManager` docstring refers to ` ests/openassetio/test/manager`
* `BUILDING.md` `pytest openassetio/tests` should ideally be `pytest openassetio/tests/python`, but minor.

**Review by feltech — APPROVED** [review]
LGTM. Other minor missing updates could be done in another PR.

**Comment by foundrytom** [comment]
> Trying to find other missed references that should have been updated, just a couple of minor ones
> 
> * `StubManager.py:StubManager` docstring refers to `tests/openassetio/test/manager`
> * `BUILDING.md` `pytest openassetio/tests` should ideally be `pytest openassetio/tests/python`, but minor.

Updated those other two.

**Review by feltech — APPROVED** [review]
LGTM squash and merge when ready

**Pull request merged**
