### PR TITLE
[Docs] Add link to working group meetings in Getting Involved section.

### PR DESCRIPTION
**Pull request by mmazerolle**
Add link to the working group meetings from the main project readme. Idea from MovieLabs wanting to attend meetings but not being able to find how.

Signed-off-by: mmazerolle <mathieu.mazerolle@foundry.com>

### CODE REVIEW

**Comment by mmazerolle** [comment]
Added DCO and component tag to commit message.

**Comment by feltech** [comment]
@mmazerolle - did you perhaps forget to push?

**Comment by foundrytom** [comment]
> @mmazerolle - did you perhaps forget to push?

I was attempting to help Matt overcome the roadblock that is DCO _and_ GPG signed commits 🙃

**Review by feltech — APPROVED** [review]

**Comment by feltech** [comment]
Please rebase on the latest `main` and force-push the branch, and I'll get it merged.

**Comment by foundrytom** [comment]
> Rebased, signed, and hopefully ready to merge.

Thanks for indulging the hoop jumping Matt, wish it wasn't so complicated!

**Pull request merged**
